first commit

diff --git a/STAR indexing b/STAR indexing
--- a/STAR indexing
+++ b/STAR indexing
@@ -1,1 +1,30 @@
 
+####STAR indexing script
+##run before the mapping wrapper
+
+
+#!/bin/bash
+#$ -cwd
+#$ -j y
+#$ -S /bin/bash
+#$ -q all.q
+#$ -M ew19289@essex.ac.uk
+#$ -m e
+#$ -l mem_free=50G
+#$ -pe smp 8
+
+source ./src/functions.sh
+
+
+STAR --runThreadN 8 --runMode genomeGenerate --genomeDir ./Mouse_ref_genome/ --genomeFastaFiles ./Mouse_ref_genome/Mus_musculus$
+
+
+if [ $? = 0 ] ; then
+        log "genome successfully indexed"
+        else
+                log "error in indexing reference genome"
+                exit 1
+fi
+
+
+
diff --git a/downloading fastq script b/downloading fastq script
--- a/downloading fastq script
+++ b/downloading fastq script
@@ -1,1 +1,30 @@
 
+###give SRRlist as input to this when running it
+
+#!/bin/bash
+
+source ./src/functions.sh
+
+SRR_LIST="$1"
+FQ_DIR="./fastq/"
+
+if [ -z $1 ] ; then
+        log "SRR list not provided"
+        exit 1
+fi
+
+####################this if statment says if argument one is empty, log that list isn't provided
+#####################and exit with exit code 1
+
+create_folder ${FQ_DIR}
+
+#####################create a folder with the name of the FQ_DIR
+
+
+
+log "Reading file ${SRR_LIST}"
+
+#################log that the file of SRR lists is being read
+
+
+
diff --git a/downloading fastq wrapper b/downloading fastq wrapper
--- a/downloading fastq wrapper
+++ b/downloading fastq wrapper
@@ -1,1 +1,54 @@
+#!/bin/bash
+#$ -cwd
+#$ -j y
+#$ -S /bin/bash
+#$ -q all.q
+#$ -M ew19289@essex.ac.uk
+#$ -m e
+#$ -l mem_free=10G
+#$ -pe smp 4
+
+source ./src/functions.sh
+
+
+SRR_CODE=$1
+FQ_DIR=$2
+
+#check inputs exist
+
+if [ $! -ne 2 ]; then
+        log "Exactly 2 inputs are needed"
+        exit 1
+fi
+
+#check inputs aren't empty
+
+if [ -z $1 ] ; then
+        log "SRR_CODE does not exist"
+        exit 1
+fi
+
+if [ -z $2 ] ; then
+        log "FQ_DIR does not exist"
+        exit 1
+fi
+
+
+log "$1: downloading from SRA"
+
+
+fastq-dump --outdir ${FQ_DIR} --split-files $SRR_CODE
+
+
+if [ $?=0 ] ; then
+        log "download complete"
+        exit
+        else
+                log "download incomplete"
+                exit 1
+fi
+
+
+#check it worked and log exit code
+
 
diff --git a/fastqc wrapper b/fastqc wrapper
--- a/fastqc wrapper
+++ b/fastqc wrapper
@@ -1,1 +1,54 @@
 
+#!/bin/bash
+#$ -cwd
+#$ -j y
+#$ -S /bin/bash
+#$ -q all.q
+#$ -M ew19289@essex.ac.uk
+#$ -m e
+#$ -l mem_free=10G
+#$ -pe smp 4
+
+source ./src/functions.sh
+
+
+FQ_CODE=$1
+FASTQC_PRE_TRIM_REPORT_DIR=$2
+
+#check inputs exist
+
+if [ $! -ne 2 ]; then
+        log "Exactly 2 inputs are needed"
+        exit 1
+fi
+
+
+#check inputs aren't empty
+
+if [ -z $1 ] ; then
+        log "FASTQ_CODE does not exist"
+        exit 1
+fi
+
+if [ -z $2 ] ; then
+        log "FQC__PRE_TRIM_REPORT_DIR does not exist"
+        exit 1
+fi
+
+
+log "$1: getting fastqc scores"
+
+
+fastqc -t 4 --outdir=${FASTQC_PRE_TRIM_REPORT_DIR} --nogroup --extract ${FQ_CODE}
+
+
+#check it worked and log exit code
+
+
+if [ $? = 0 ] ; then
+        log "FASTQC score obtained"
+        else
+                log "error obtaining FASTQ"
+                exit 1
+fi
+
diff --git a/trimming wrapper b/trimming wrapper
--- a/trimming wrapper
+++ b/trimming wrapper
@@ -1,1 +1,41 @@
+#!/bin/bash
+
+#$ -cwd
+#$ -j y
+#$ -S /bin/bash
+#$ -q all.q
+#$ -M ew19289@essex.ac.uk
+#$ -m e
+#$ -pe smp 4
+
+#expected arguments
+# 1 - fastq file for R1
+# 2 - trimming directory for output
+# 3 - report directory for fastqc
+# 4 - fastq file for R2 (optional, paired end only)
+
+source ./src/functions.sh
+
+log "processing $1"
+
+fastqcArgs="-t 4 --outdir $3 --nogroup --extract"
+
+#decide if single or paired end using test for the empty string
+if [ ! -z "$4" ]; then
+        log "Paired end reads supplied"
+        log "running trim galore -o $2 --paired --fastqc --fastqc_args ${fastqcArgs} ${1} ${4}"
+        trim_galore -o $2 --paired --fastqc --fastqc_args "${fastqcArgs}" ${1} ${4}
+else
+        log "Single end reads supplied"
+        log " Running trim_galore -o $2 --fastqc --fastqc_args ${fastqcArgs} ${1}"
+        trim_galore -o $2 --fastqc --fastqc_args "${fastqcArgs}" ${1}
+fi
+
+#check it worked
+if [ $? -ne "0" ] ; then
+        log "Error trimming reads from $1"
+else
+        log "trimming complete"
+fi
+
 
